[package]
name = "todo-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.28.0"
crossterm = "0.28.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
dirs = "6.0.0"
anyhow = "1.0.97"
thiserror = "2.0.12"
